# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Music',
            new_name='Lit',
        ),
    ]
