# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='music/audios', verbose_name='音频'),
        ),
    ]
