# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='life',
            name='status',
            field=models.CharField(choices=[('0', '未审核'), ('1', '已审核')], max_length=20, verbose_name='是否审核'),
        ),
        migrations.AlterField(
            model_name='life',
            name='tag',
            field=models.CharField(choices=[('0', 'food'), ('1', 'creation'), ('2', 'pet'), ('3', 'health'), ('4', 'emotion'), ('5', 'flower')], max_length=30, verbose_name='标签'),
        ),
    ]
