# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0002_auto_20170410_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='life',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='life/images', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='life',
            name='zan',
            field=models.IntegerField(default=0, verbose_name='赞'),
        ),
    ]
