# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0005_auto_20170411_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='life',
            name='image',
            field=models.ImageField(blank=True, help_text='图像尺寸: 130*170', null=True, upload_to='life/images', verbose_name='封面'),
        ),
    ]
