# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 14:24
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedtime', models.DateTimeField(auto_now_add=True, verbose_name='反馈时间')),
                ('feedpersonname', models.CharField(blank=True, default='佚名', max_length=30, null=True, verbose_name='反馈人姓名')),
                ('feedpersonemail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='反馈人邮箱')),
                ('feedcontent', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='反馈内容')),
                ('status', models.CharField(choices=[('0', '未查看'), ('1', '已查看')], max_length=10, verbose_name='是否已查看')),
            ],
        ),
    ]
