# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whole', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedcontent',
        ),
        migrations.AddField(
            model_name='feedback',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='反馈内容'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedbackfile',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='附件'),
        ),
    ]
