# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whole', '0002_auto_20170415_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedbackimage',
            field=models.ImageField(blank=True, null=True, upload_to='feedback_images', verbose_name='附件图片'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedbackfile',
            field=models.FileField(blank=True, null=True, upload_to='feedback_files', verbose_name='附件文件'),
        ),
    ]
