# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whole', '0003_auto_20170416_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedbackfile',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='feedbackimage',
        ),
    ]
